Repository CS2103-AY1819S1-W12-2/main, pull requests merged in 2018-10, with the labels that each got.

#72 Add interest calculation feature to the application
  README.adoc
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/Mode.java
  src/main/java/seedu/address/commons/core/CalendarManager.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AnalyticsCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/InterestCommand.java
  src/main/java/seedu/address/logic/commands/InterestRate.java
  src/main/java/seedu/address/logic/commands/ModeCommand.java
  src/main/java/seedu/address/logic/commands/UploadPhotoCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FinancialDatabaseParser.java
  src/main/java/seedu/address/logic/parser/InterestCommandParser.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/Deadline.java
  src/main/java/seedu/address/model/transaction/Interest.java
  src/main/java/seedu/address/model/transaction/InterestScheme.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/storage/XmlAdaptedTransaction.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/TransactionListCard.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/guitests/guihandles/TransactionCardHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AnalyticsCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
  src/test/java/seedu/address/ui/TransactionListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.High

#80 Add sort command and tests
  allTest.sh
  src/main/java/seedu/address/commons/core/CalendarManager.java
  src/main/java/seedu/address/logic/commands/CalendarCommand.java
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/InterestCommand.java
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FinancialDatabaseParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/transaction/Amount.java
  src/main/java/seedu/address/model/transaction/Deadline.java
  src/main/java/seedu/address/model/transaction/Type.java
  src/test/java/guitests/GuiRobot.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AnalyticsCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ConvertCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/InterestCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/transaction/DeadlineTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.Medium, type.Story

#79 add NextTransactionCommand and test cases
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/NextTransactionCommand.java
  src/main/java/seedu/address/logic/parser/FinancialDatabaseParser.java
  src/main/java/seedu/address/model/transaction/DeadlineContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/transaction/FieldContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AnalyticsCommandTest.java
  src/test/java/seedu/address/logic/commands/NextTransactionCommandTest.java
Labels: priority.Medium
